export default interface SelectedHotel {
    id: string,
    name: string,
    starRating: string,
    images: {url: string, alt: string}[],
    description: string,
    facilities: {code: number}[],
    country: string,
    countryCode: string,
    postcode: string,
    town: string,
    address1: string,
    address2: string,
    position: {latitude: string, longitude: string, timezone: string},
    telephone: string,
    email: string,
    checkInHours: string,
    checkInMinutes: string,
    checkOutHours: string,
    checkOutMinutes: string,
};